name: e2e-rerun

on:
  workflow_run:
    workflows:
      - e2e
    types:
      - completed

jobs:
  rerun-first-attempt-failure:
    if: |
      github.event.workflow_run.conclusion == 'failure' &&
      github.event.workflow_run.run_attempt == 1
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      actions: write # To rerun workflows
    steps:
      - uses: int128/rerun-workflows-action@9a774a5c2db202da4c12698a3933084fe9b114f1 # v1.3.0
        with:
          event: ${{ github.event.workflow_run.event }}
          sha: ${{ github.event.workflow_run.head_sha }}
