name: wait-for-workflows

on:
  pull_request:

jobs:
  wait-for-workflows:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    permissions:
      actions: write # To rerun workflows.
      checks: read
    steps:
      # Wait for the e2e workflow and rerun it.
      - uses: int128/wait-for-workflows-action@456c3b39b5e122319b40ffad07b8179731f8291c # v1.82.0
        continue-on-error: true
        with:
          filter-workflow-names: e2e
      - uses: int128/rerun-workflows-action@7e6c9b83b8df69931f8e295ffb8c4b6b079d38ed # v1.6.0

      # Finally, wait for all workflows.
      - uses: int128/wait-for-workflows-action@456c3b39b5e122319b40ffad07b8179731f8291c # v1.82.0
